version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: .Dockerfile
    container_name: vaultsync_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached
    networks:
      - laravel
    depends_on:
      - db
    environment:
      PHP_IDE_CONFIG: "serverName=laravel"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: vaultsync
      DB_USERNAME: vaultsync
      DB_PASSWORD: vaultsync
      APP_DEBUG: false
      APP_ENV: local

  web:
    image: nginx:1.25-alpine
    container_name: laravel_web
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.4
    container_name: vaultsync
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: vaultsync
      MYSQL_USER: vaultsync
      MYSQL_PASSWORD: vaultsync
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: laravel_chrome
    shm_size: 2gb
    ports:
      - "4444:4444"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data:
