version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: .Dockerfile
    container_name: vaultsync_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached
      - /var/www/html/vendor
      - /var/www/html/storage
      - /var/www/html/bootstrap/cache
    networks:
      - laravel
    depends_on:
      - db
    environment:
      PHP_IDE_CONFIG: "serverName=laravel"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: vaultsync
      DB_USERNAME: vaultsync
      DB_PASSWORD: vaultsync
      APP_DEBUG: true
      APP_ENV: local
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
      CACHE_STORE: file
      APP_KEY: base64:R26Y3CtC6asHkA7dDBnkX7YbdEnmXnutIUMloB2UlVU=
      VITE_PORT: 5173

  vite:
    build:
      context: .
      dockerfile: .Dockerfile
    container_name: vaultsync_vite
    working_dir: /var/www/html
    command: npm run dev
    volumes:
      - .:/var/www/html:cached
      - /var/www/html/node_modules
    ports:
      - "5173:5173"
    networks:
      - laravel
    environment:
      APP_ENV: local

  web:
    image: nginx:1.25-alpine
    container_name: laravel_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - vite
    networks:
      - laravel

  db:
    image: mysql:8.4
    container_name: vaultsync
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: vaultsync
      MYSQL_USER: vaultsync
      MYSQL_PASSWORD: vaultsync
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data:
